package NFS;


/**
* NFS/Data.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NFS.idl
* Tuesday, January 26, 2016 6:40:19 PM CET
*/

public abstract class Data implements org.omg.CORBA.portable.StreamableValue
{
  public String id = null;
  public int contents = (int)0;

  private static String[] _truncatable_ids = {
    NFS.DataHelper.id ()
  };

  public String[] _truncatable_ids() {
    return _truncatable_ids;
  }

  public void _read (org.omg.CORBA.portable.InputStream istream)
  {
    this.id = istream.read_string ();
    this.contents = istream.read_long ();
  }

  public void _write (org.omg.CORBA.portable.OutputStream ostream)
  {
    ostream.write_string (this.id);
    ostream.write_long (this.contents);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return NFS.DataHelper.type ();
  }
} // class Data
