package NFS;


/**
* NFS/ProxyOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NFS.idl
* Tuesday, January 26, 2016 6:47:22 PM CET
*/

public interface ProxyOperations 
{
  String pwd ();
  String ls ();
  String history ();
  String mkdir (String dirName);
  String mkFile (String fileName);
  String cd (String directory);
  String ps ();
} // interface ProxyOperations
