package NFS;


/** Specifies the legal operations available in the system.
 * 
 * 
* NFS/Proxy.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NFS.idl
* Wednesday, January 27, 2016 5:31:23 PM CET
*/

public interface Proxy extends ProxyOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Proxy
